import requests
from requests.exceptions import SSLError
# import certifi
import sys

session = requests.Session()

# session.cookies.set('cookieconsent_northernillinoisuniversity', 'dismiss', domain='.niu.edu', path='/', secure=True, rest={'HttpOnly': True})

cert_path = "/home/matt/test/cs-niu-edu-chain.pem"

try:
    response = session.get(sys.argv[1], verify=cert_path)
except SSLError as e:
    print(f"SSL Error: {e}")

print(response.content)


session_cookie = session.cookies.get("")
print(session_cookie)

# cookie_path = "/"
# domain = ".babbage.cs.niu.edu"
#
#
# if session_cookie:
#     print(session_cookie)
#     cookie_line = f"{domain}\tTRUE\t{cookie_path}\tFALSE\t0\tAGSESSID\t{session_cookie}"
#
#     with open("cookies_netscape.txt", "w") as f:
#         f.write("# Netscape HTTP Cookie File\n")
#         f.write("# This file was generated by Python script\n")
#         f.write(cookie_line + "\n")
#
#     print(f"session id cookie sucesfully written to cookies_netscape.txt")
# else:
#     print(f"error getting session id cookie....")
#
#
